version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4.1-management
    container_name: rabbitmq_toolkit
    ports:
      - "5672:5672"      # AMQP port
      - "15672:15672"    # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: testes
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge